package DAO;

public class DOT_THUCHIEN_SUACHUA_BAODUONG {
	private int MA_DOT_THUCHIEN_SUACHUA_BAODUONG;
	private String TEN_DOT_THUCHIEN_SUACHUA_BAODUONG;
	private int MUC_KINH_PHI;
	private int SUACHUA_BAODUONG;
	private int LOAI_PHUONG_TIEN;
	private String MO_TA;
	private int MA_QUATRINH_DEXUAT_THUCHIEN;
	private int MA_QUATRINH_NGHIEMTHU_QUYETTOAN;
	private int MA_NGUONSUACHUA_BAODUONG;

	public int getMA_DOT_THUCHIEN_SUACHUA_BAODUONG() {
		return MA_DOT_THUCHIEN_SUACHUA_BAODUONG;
	}

	public void setMA_DOT_THUCHIEN_SUACHUA_BAODUONG(int mA_DOT_THUCHIEN_SUACHUA_BAODUONG) {
		MA_DOT_THUCHIEN_SUACHUA_BAODUONG = mA_DOT_THUCHIEN_SUACHUA_BAODUONG;
	}

	public String getTEN_DOT_THUCHIEN_SUACHUA_BAODUONG() {
		return TEN_DOT_THUCHIEN_SUACHUA_BAODUONG;
	}

	public void setTEN_DOT_THUCHIEN_SUACHUA_BAODUONG(String tEN_DOT_THUCHIEN_SUACHUA_BAODUONG) {
		TEN_DOT_THUCHIEN_SUACHUA_BAODUONG = tEN_DOT_THUCHIEN_SUACHUA_BAODUONG;
	}

	public int getMUC_KINH_PHI() {
		return MUC_KINH_PHI;
	}

	public void setMUC_KINH_PHI(int mUC_KINH_PHI) {
		MUC_KINH_PHI = mUC_KINH_PHI;
	}

	public int getSUACHUA_BAODUONG() {
		return SUACHUA_BAODUONG;
	}

	public void setSUACHUA_BAODUONG(int sUACHUA_BAODUONG) {
		SUACHUA_BAODUONG = sUACHUA_BAODUONG;
	}

	public int getLOAI_PHUONG_TIEN() {
		return LOAI_PHUONG_TIEN;
	}

	public void setLOAI_PHUONG_TIEN(int lOAI_PHUONG_TIEN) {
		LOAI_PHUONG_TIEN = lOAI_PHUONG_TIEN;
	}

	public String getMO_TA() {
		return MO_TA;
	}

	public void setMO_TA(String mO_TA) {
		MO_TA = mO_TA;
	}

	public int getMA_QUATRINH_DEXUAT_THUCHIEN() {
		return MA_QUATRINH_DEXUAT_THUCHIEN;
	}

	public void setMA_QUATRINH_DEXUAT_THUCHIEN(int mA_QUATRINH_DEXUAT_THUCHIEN) {
		MA_QUATRINH_DEXUAT_THUCHIEN = mA_QUATRINH_DEXUAT_THUCHIEN;
	}

	public int getMA_QUATRINH_NGHIEMTHU_QUYETTOAN() {
		return MA_QUATRINH_NGHIEMTHU_QUYETTOAN;
	}

	public void setMA_QUATRINH_NGHIEMTHU_QUYETTOAN(int mA_QUATRINH_NGHIEMTHU_QUYETTOAN) {
		MA_QUATRINH_NGHIEMTHU_QUYETTOAN = mA_QUATRINH_NGHIEMTHU_QUYETTOAN;
	}

	public int getMA_NGUONSUACHUA_BAODUONG() {
		return MA_NGUONSUACHUA_BAODUONG;
	}

	public void setMA_NGUONSUACHUA_BAODUONG(int mA_NGUONSUACHUA_BAODUONG) {
		MA_NGUONSUACHUA_BAODUONG = mA_NGUONSUACHUA_BAODUONG;
	}

}
