package DAO;

import java.util.Date;

public class GIAI_DOAN_THUC_HIEN {
	private int MA_GIAI_DOAN_THUC_HIEN;
	private Date THOI_DIEM_BAT_DAU;
	private int THOI_GIAN_DU_KIEN_HOAN_THANH;
	private Date THOI_DIEM_CHUYEN_GIAO;
	private Date THOI_DIEM_HOAN_THANH;
	private String GHI_CHU;
	private int MA_QUATRINH_DEXUAT_THUCHIEN;

	public int getMA_GIAI_DOAN_THUC_HIEN() {
		return MA_GIAI_DOAN_THUC_HIEN;
	}

	public void setMA_GIAI_DOAN_THUC_HIEN(int mA_GIAI_DOAN_THUC_HIEN) {
		MA_GIAI_DOAN_THUC_HIEN = mA_GIAI_DOAN_THUC_HIEN;
	}

	public Date getTHOI_DIEM_BAT_DAU() {
		return THOI_DIEM_BAT_DAU;
	}

	public void setTHOI_DIEM_BAT_DAU(Date tHOI_DIEM_BAT_DAU) {
		THOI_DIEM_BAT_DAU = tHOI_DIEM_BAT_DAU;
	}

	public int getTHOI_GIAN_DU_KIEN_HOAN_THANH() {
		return THOI_GIAN_DU_KIEN_HOAN_THANH;
	}

	public void setTHOI_GIAN_DU_KIEN_HOAN_THANH(int tHOI_GIAN_DU_KIEN_HOAN_THANH) {
		THOI_GIAN_DU_KIEN_HOAN_THANH = tHOI_GIAN_DU_KIEN_HOAN_THANH;
	}

	public Date getTHOI_DIEM_CHUYEN_GIAO() {
		return THOI_DIEM_CHUYEN_GIAO;
	}

	public void setTHOI_DIEM_CHUYEN_GIAO(Date tHOI_DIEM_CHUYEN_GIAO) {
		THOI_DIEM_CHUYEN_GIAO = tHOI_DIEM_CHUYEN_GIAO;
	}

	public Date getTHOI_DIEM_HOAN_THANH() {
		return THOI_DIEM_HOAN_THANH;
	}

	public void setTHOI_DIEM_HOAN_THANH(Date tHOI_DIEM_HOAN_THANH) {
		THOI_DIEM_HOAN_THANH = tHOI_DIEM_HOAN_THANH;
	}

	public String getGHI_CHU() {
		return GHI_CHU;
	}

	public void setGHI_CHU(String gHI_CHU) {
		GHI_CHU = gHI_CHU;
	}

	public int getMA_QUATRINH_DEXUAT_THUCHIEN() {
		return MA_QUATRINH_DEXUAT_THUCHIEN;
	}

	public void setMA_QUATRINH_DEXUAT_THUCHIEN(int mA_QUATRINH_DEXUAT_THUCHIEN) {
		MA_QUATRINH_DEXUAT_THUCHIEN = mA_QUATRINH_DEXUAT_THUCHIEN;
	}

}
