package DAO;

public class NHOMTAISAN_CAP_III {
	int MA_NHOMTAISAN_CAP_III;
	String TEN_NHOMTAISAN_CAP_III;
	int MA_NHOMTAISAN_CAP_II;

	public int getMA_NHOMTAISAN_CAP_III() {
		return MA_NHOMTAISAN_CAP_III;
	}

	public void setMA_NHOMTAISAN_CAP_III(int mA_NHOMTAISAN_CAP_III) {
		MA_NHOMTAISAN_CAP_III = mA_NHOMTAISAN_CAP_III;
	}

	public String getTEN_NHOMTAISAN_CAP_III() {
		return TEN_NHOMTAISAN_CAP_III;
	}

	public void setTEN_NHOMTAISAN_CAP_III(String tEN_NHOMTAISAN_CAP_III) {
		TEN_NHOMTAISAN_CAP_III = tEN_NHOMTAISAN_CAP_III;
	}

	public int getMA_NHOMTAISAN_CAP_II() {
		return MA_NHOMTAISAN_CAP_II;
	}

	public void setMA_NHOMTAISAN_CAP_II(int mA_NHOMTAISAN_CAP_II) {
		MA_NHOMTAISAN_CAP_II = mA_NHOMTAISAN_CAP_II;
	}
}
