package DAO;

public class NHOM_DONVI_THAMGIA_THONGKE {
	private int MA_NHOM_DONVI_THAMGIA_THONGKE;
	private String TEN_NHOM_DONVI_THAMGIA_THONGKE;
	private int MA_KYHAN;

	public int getMA_NHOM_DONVI_THAMGIA_THONGKE() {
		return MA_NHOM_DONVI_THAMGIA_THONGKE;
	}

	public void setMA_NHOM_DONVI_THAMGIA_THONGKE(int mA_NHOM_DONVI_THAMGIA_THONGKE) {
		MA_NHOM_DONVI_THAMGIA_THONGKE = mA_NHOM_DONVI_THAMGIA_THONGKE;
	}

	public String getTEN_NHOM_DONVI_THAMGIA_THONGKE() {
		return TEN_NHOM_DONVI_THAMGIA_THONGKE;
	}

	public void setTEN_NHOM_DONVI_THAMGIA_THONGKE(String tEN_NHOM_DONVI_THAMGIA_THONGKE) {
		TEN_NHOM_DONVI_THAMGIA_THONGKE = tEN_NHOM_DONVI_THAMGIA_THONGKE;
	}

	public int getMA_KYHAN() {
		return MA_KYHAN;
	}

	public void setMA_KYHAN(int mA_KYHAN) {
		MA_KYHAN = mA_KYHAN;
	}
}
