package DAO;

public class NHOMTAISAN_CAP_I {
	int MA_NHOMTAISAN_CAP_I;
	String TEN_NHOMTAISAN_CAP_I;

	public int getMA_NHOMTAISAN_CAP_I() {
		return MA_NHOMTAISAN_CAP_I;
	}

	public void setMA_NHOMTAISAN_CAP_I(int mA_NHOMTAISAN_CAP_I) {
		MA_NHOMTAISAN_CAP_I = mA_NHOMTAISAN_CAP_I;
	}

	public String getTEN_NHOMTAISAN_CAP_I() {
		return TEN_NHOMTAISAN_CAP_I;
	}

	public void setTEN_NHOMTAISAN_CAP_I(String tEN_NHOMTAISAN_CAP_I) {
		TEN_NHOMTAISAN_CAP_I = tEN_NHOMTAISAN_CAP_I;
	}
}
