package DAO;

public class NHOMTAISAN_CAP_IV {
	int MA_NHOMTAISAN_CAP_IV;
	String TEN_NHOMTAISAN_CAP_IV;
	int MA_NHOMTAISAN_CAP_III;

	public int getMA_NHOMTAISAN_CAP_IV() {
		return MA_NHOMTAISAN_CAP_IV;
	}

	public void setMA_NHOMTAISAN_CAP_IV(int mA_NHOMTAISAN_CAP_IV) {
		MA_NHOMTAISAN_CAP_IV = mA_NHOMTAISAN_CAP_IV;
	}

	public String getTEN_NHOMTAISAN_CAP_IV() {
		return TEN_NHOMTAISAN_CAP_IV;
	}

	public void setTEN_NHOMTAISAN_CAP_IV(String tEN_NHOMTAISAN_CAP_IV) {
		TEN_NHOMTAISAN_CAP_IV = tEN_NHOMTAISAN_CAP_IV;
	}

	public int getMA_NHOMTAISAN_CAP_III() {
		return MA_NHOMTAISAN_CAP_III;
	}

	public void setMA_NHOMTAISAN_CAP_III(int mA_NHOMTAISAN_CAP_III) {
		MA_NHOMTAISAN_CAP_III = mA_NHOMTAISAN_CAP_III;
	}
}
