package DAO;

public class QUATRINH_NGHIEMTHU_QUYETTOAN {
	private int MA_QUATRINH_NGHIEMTHU_QUYETTOAN;
	private String TEN_QUA_TRINH;

	public int getMA_QUATRINH_NGHIEMTHU_QUYETTOAN() {
		return MA_QUATRINH_NGHIEMTHU_QUYETTOAN;
	}

	public void setMA_QUATRINH_NGHIEMTHU_QUYETTOAN(int mA_QUATRINH_NGHIEMTHU_QUYETTOAN) {
		MA_QUATRINH_NGHIEMTHU_QUYETTOAN = mA_QUATRINH_NGHIEMTHU_QUYETTOAN;
	}

	public String getTEN_QUA_TRINH() {
		return TEN_QUA_TRINH;
	}

	public void setTEN_QUA_TRINH(String tEN_QUA_TRINH) {
		TEN_QUA_TRINH = tEN_QUA_TRINH;
	}

}
